"""F1: ポイントインタイム・ユニバースの機械生成.

東証全体（プライム/スタンダード/グロース + 旧区分）の普通株から、
指定時点で実際に上場していた銘柄を J-Quants `/equities/master?date=` で取得し、
価格帯・流動性でフィルタしてユニバース CSV を生成する。

- 生存者バイアスの緩和: 各時点の master には後に上場廃止となる銘柄が
  当時の姿で含まれる（実測確認済み: 2022-01-04 → 現在で475銘柄が消滅）
- フィルタ（生成時）: 普通株（ProdCat=011）/ 本則市場（TOKYO PRO MARKET 除外）/
  終値 ¥100〜3,000 / 5日平均売買代金 ≥ ¥100M（runtime screener と同じ閾値）
- ファンダ系フィルタ（時価総額・PBR・自己資本比率）は runtime screener が
  毎日適用するためユニバース生成では課さない

Usage:
    # 四半期スナップショット一括生成（2022Q1〜2026Q3 → data/universe_pit/*.csv）
    python scripts/build_universe.py --quarters 2022Q1 2026Q3

    # 単一時点（四半期定期更新・本番ユニバース候補の生成）
    python scripts/build_universe.py --as-of 2026-07-01 --out data/universe_pit/2026Q3.csv
"""
import argparse
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from squant.config.constants import (  # noqa: E402
    LIQUIDITY_MIN_JPY,
    PRICE_MAX,
    PRICE_MIN,
)
from squant.utils.jst import is_tse_trading_day  # noqa: E402

# 本則市場（現行 + 2022-04 市場再編前の旧区分）。TOKYO PRO MARKET は対象外
ELIGIBLE_MARKETS = {
    "プライム", "スタンダード", "グロース",
    "東証一部", "東証二部", "マザーズ", "JASDAQ スタンダード", "JASDAQ グロース",
}
COMMON_STOCK_PRODCAT = "011"
LIQUIDITY_WINDOW_DAYS = 5

_OUT_DIR = Path(__file__).resolve().parent.parent / "data" / "universe_pit"


def code_to_ticker(code: str) -> str | None:
    """J-Quants 5桁コード → 内部 ticker 形式（'72030' → '7203.T'）。

    普通株は末尾 '0'。それ以外（優先株等）は None。
    """
    if len(code) == 5 and code.endswith("0"):
        return f"{code[:-1]}.T"
    return None


def trading_days_before(as_of: date, n: int) -> list[date]:
    """as_of の前日から遡って n 営業日（古い順）。"""
    days: list[date] = []
    d = as_of - timedelta(days=1)
    while len(days) < n:
        if is_tse_trading_day(d):
            days.append(d)
        d -= timedelta(days=1)
    return sorted(days)


def generate_universe(
    master_rows: list[dict],
    bars_by_day: list[list[dict]],
    *,
    price_min: float = float(PRICE_MIN),
    price_max: float = float(PRICE_MAX),
    liquidity_min_jpy: float = float(LIQUIDITY_MIN_JPY),
) -> list[str]:
    """時点マスタ + 直近数日の全銘柄バーからユニバースを生成する（純関数）。

    - master_rows: fetch_equities_master(as_of) の行
    - bars_by_day: 直近 LIQUIDITY_WINDOW_DAYS 営業日分の fetch_bars_for_date 結果
      （価格は最終日の終値、流動性は全日の Va 平均で判定）
    """
    eligible_codes = {
        r["Code"] for r in master_rows
        if r.get("ProdCat") == COMMON_STOCK_PRODCAT
        and r.get("MktNm") in ELIGIBLE_MARKETS
    }

    # 売買代金の平均と最終日終値
    va_sum: dict[str, float] = {}
    va_n: dict[str, int] = {}
    last_close: dict[str, float] = {}
    for day_rows in bars_by_day:
        for b in day_rows:
            code = b.get("Code", "")
            if code not in eligible_codes:
                continue
            va = b.get("Va")
            if va is not None:
                va_sum[code] = va_sum.get(code, 0.0) + float(va)
                va_n[code] = va_n.get(code, 0) + 1
            close = b.get("AdjC") if b.get("AdjC") is not None else b.get("C")
            if close is not None:
                last_close[code] = float(close)  # 日付昇順なので最終日が残る

    out: list[str] = []
    for code in sorted(eligible_codes):
        close = last_close.get(code)
        if close is None or not (price_min <= close <= price_max):
            continue
        n = va_n.get(code, 0)
        if n == 0 or va_sum[code] / n < liquidity_min_jpy:
            continue
        ticker = code_to_ticker(code)
        if ticker:
            out.append(ticker)
    return out


def quarter_first_trading_day(year: int, quarter: int) -> date:
    d = date(year, 3 * (quarter - 1) + 1, 1)
    while not is_tse_trading_day(d):
        d += timedelta(days=1)
    return d


def iter_quarters(start: str, end: str):
    """'2022Q1' 〜 '2026Q3' を (year, q) で列挙する。"""
    y0, q0 = int(start[:4]), int(start[5])
    y1, q1 = int(end[:4]), int(end[5])
    y, q = y0, q0
    while (y, q) <= (y1, q1):
        yield y, q
        q += 1
        if q == 5:
            y, q = y + 1, 1


def _build_one(client, as_of: date, out_path: Path) -> int:
    master = client.fetch_equities_master(as_of)
    if not master:
        print(f"  {as_of}: master 取得失敗 — スキップ", file=sys.stderr)
        return 0
    bars = [client.fetch_bars_for_date(d)
            for d in trading_days_before(as_of, LIQUIDITY_WINDOW_DAYS)]
    universe = generate_universe(master, bars)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# point-in-time universe as of {as_of} (generated by build_universe.py)",
        f"# filters: common stock (ProdCat=011), main markets, close ¥{PRICE_MIN}-{PRICE_MAX},",
        f"#          {LIQUIDITY_WINDOW_DAYS}d avg trading value >= ¥{LIQUIDITY_MIN_JPY:,}",
        "ticker",
        *universe,
    ]
    out_path.write_text("\n".join(lines) + "\n")
    print(f"  {as_of}: {len(universe)} tickers → {out_path}")
    return len(universe)


def main() -> int:
    parser = argparse.ArgumentParser(description="ポイントインタイム・ユニバース生成（F1）")
    parser.add_argument("--quarters", nargs=2, metavar=("FROM", "TO"),
                        help="例: --quarters 2022Q1 2026Q3（四半期初営業日でスナップショット）")
    parser.add_argument("--as-of", default=None, help="単一時点 YYYY-MM-DD")
    parser.add_argument("--out", default=None, help="単一時点モードの出力先 CSV")
    args = parser.parse_args()

    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass
    import os

    from squant.infrastructure.jquants_client import JQuantsClient
    client = JQuantsClient(
        api_key=os.environ.get("JQUANTS_API_KEY", ""),
        requests_per_minute=int(os.environ.get("JQUANTS_RPM", "50")),
    )

    if args.quarters:
        for y, q in iter_quarters(args.quarters[0], args.quarters[1]):
            as_of = quarter_first_trading_day(y, q)
            _build_one(client, as_of, _OUT_DIR / f"{y}Q{q}.csv")
        return 0

    if args.as_of:
        as_of = date.fromisoformat(args.as_of)
        out = Path(args.out) if args.out else _OUT_DIR / f"asof_{as_of}.csv"
        _build_one(client, as_of, out)
        return 0

    parser.error("--quarters か --as-of を指定してください")
    return 1


if __name__ == "__main__":
    sys.exit(main())
